backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets/images/uploads" # Media files will be stored in the repo under src/assets/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /assets

collections:
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "src/content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Type of Article",
          name: "type",
          widget: "select",
          options: ["blog", "project"],
        }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "contribution"
    label: "Contribution"
    folder: "src/content/contributions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: slug
    extension: json
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Project", name: "projectName", widget: "string" }
      - { label: "Project URL", name: "projectUrl", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "URL", name: "url", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
